version: '3.8'
services:
  web:
    build: .
    command: npm run dev
    environment:
      - NODE_ENV=development
      - MYSQL_DSN=mysql://nofdoet:nofdoetpass@mysql:3306/nofdoet
      - BCRYPT_COST=${BCRYPT_COST:-12}
      - SESSION_SECRET=dev-secret-change
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nofdoet
      MYSQL_USER: nofdoet
      MYSQL_PASSWORD: nofdoetpass
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data:
